### PR TITLE
User login test

### PR DESCRIPTION
**Pull request by stedmana**
Created test. Used a stub for TestClient as i could not get it working properly

### CODE REVIEW

**Comment by kevinch8** [comment]
It would seem that this includes the tests for register as well, so it may be a good idea not to include those tests or merge conflicts will arise. Otherwise, change the name from test_mainLOGIN.py to test_login.py as a filename.

**Comment by stedmana** [comment]
I'm just about to push a version with the file renamed. When you say not include those files, should i remove them from my disk and commit that change? then i guess they would be merged back in when this branch merges with master?

**Comment by kevinch8** [comment]
> I'm just about to push a version with the file renamed. When you say not include those files, should i remove them from my disk and commit that change? then i guess they would be merged back in when this branch merges with master?

Yes, in master there will be no problem since you both are working in different files. However, consider the case where I approve your PR and Aaron change his login file, he will have to deal with conflicts because master now contains a different login file!

**Comment by stedmana** [comment]
Great point! I'll change both those things and create a new pull request

**Pull request closed without merging**
